### ISSUE TITLE
lwm2m samples are not up to date following LWM2M API change

### ISSUE THREAD

**Issue by kartben** [solettaproject/soletta-small-oses-samples#16]
See https://github.com/solettaproject/soletta/issues/1688
I can try to propose a patch but I wonder if there's a way not to duplicate the samples in the first place ?

**Comment by glima** [comment]
Thanks for the tip, @kartben. We have though about not replicating those too, but have not had the time to attack the issue yet. It would be nice to have the patch, too, of course.

**Comment by bdilly** [comment]
fixed, thanks for reporting this issue

at some point it would be nice to have this repository merged to soletta and avoid code duplication
