### ISSUE TITLE
Soletta and RIOT-OS

### ISSUE THREAD

**Issue by mattiantonini** [solettaproject/soletta-small-oses-samples#22]
Hi!
I would like to add soletta in RIOT. I've followed all instructions, but when I type

`RIOTBASE=/path/to/RIOT make -C ../BUILD/ riot BOARD=samr21-xpro`

It downloads the soletta git and it tries the compilation, and it fails. The output is in the attached file.
[output.txt](https://github.com/solettaproject/soletta-small-oses-samples/files/348069/output.txt)

How can I fix this problem?

**Comment by glima** [comment]
- Mattia Antonini notifications@github.com [2016-07-05 08:27:19 -0700]:

> Hi!
> I would like to add soletta in RIOT. I've followed all instructions, but when I type
> 
> `RIOTBASE=/path/to/RIOT make -C ../BUILD/ riot BOARD=samr21-xpro`
> 
> It downloads the soletta git and it tries the compilation. The output is in the attached file.
> [output.txt](https://github.com/solettaproject/soletta-small-oses-samples/files/348069/output.txt)
> 
> How can I fix this problem?

I confirm this issue, thanks for reporting. Before I proceed,
@ibriano, do we use that new Makefile.smallos from Soletta elsewhere
yet or document how to do so?

> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/solettaproject/soletta-small-oses-samples/issues/22

## 

Gustavo Lima Chaves
Intel - Open Source Technology Center

**Comment by ibriano** [comment]
On Tue, 05 Jul 2016 09:40:51 -0700, Gustavo Lima Chaves wrote:

> - Mattia Antonini notifications@github.com [2016-07-05 08:27:19 -0700]:
> 
> > Hi!
> > I would like to add soletta in RIOT. I've followed all instructions, but when I type
> > 
> > `RIOTBASE=/path/to/RIOT make -C ../BUILD/ riot BOARD=samr21-xpro`
> > 
> > It downloads the soletta git and it tries the compilation. The output is in the attached file.
> > [output.txt](https://github.com/solettaproject/soletta-small-oses-samples/files/348069/output.txt)
> > 
> > How can I fix this problem?
> 
> I confirm this issue, thanks for reporting. Before I proceed,
> @ibriano, do we use that new Makefile.smallos from Soletta elsewhere
> yet or document how to do so?

Not really, I made it to help with porting to various OSes but when I
went to fix up the RIOT package to send it upstream it ended up
conflicting with RIOT's own way to handle external packages.

The problem with the compiler, as I see in the log, is that RIOT exports
a CC variable with the full name of the compiler, and there's been a
relatively recent change in Soletta's build system to take CC as well as
TOOLCHAIN_PREFIX, that's set in the Makefile in RIOT's pkg for Soletta.
Adding an 'unexport CC' in that Makefile should let the build continue
with the correct name for the compiler.

**Comment by mattiantonini** [comment]
I solved that problem, and I've modified the Makefile.include (in libsoletta) with the correct path ((RIOTBASE)/pkg/libsoletta/soletta/build/soletta_sysrootarm-none-eabi-/include/soletta) of .h files. Now, it compiles but when linker links all something goes wrong, and this is the 
[output.txt](https://github.com/solettaproject/soletta-small-oses-samples/files/350131/output.txt)
It can be related to my path settings. I'm looking for a solution, but any suggestion is welcome :)

**Comment by ibriano** [comment]
On Wed, 06 Jul 2016 07:53:30 -0700, Mattia Antonini wrote:

> I solved that problem, and I've modified the Makefile.include (in libsoletta) with the correct path ((RIOTBASE)/pkg/libsoletta/soletta/build/soletta_sysrootarm-none-eabi-/include/soletta) of .h files. Now, it compiles but when linker links all something goes wrong, and this is the 

You shouldn't need to do that, but I guess you need to add another line
to the Makefile in the RIOT package
unexport PREFIX

That should make the build path for Soletta correct.

> [output.txt](https://github.com/solettaproject/soletta-small-oses-samples/files/350131/output.txt)
> It can be related to my path settings. I'm looking for a solution, but any suggestion is welcome :)

I have no idea about this, I'd need to check, but I guess the
libsolettashared.a change may be related.

**Comment by bdilly** [comment]
Hey @mattiantonini ,

I've faced many build issues with these samples but I believe all of them are gone now (including the one you mentioned) after a few fixes.

So I'm closing this issue. Please reopen it (or open new issues) if anything goes wrong.

Thanks
