### ISSUE TITLE
Integer Overflow in sol-lwm2m-client.c

### ISSUE THREAD

**Issue by mattiantonini** [solettaproject/soletta-small-oses-samples#29]
Hi!
I'm trying to compile soletta-coap-server for RIOT but it fails, log in 
[output.txt](https://github.com/solettaproject/soletta-small-oses-samples/files/400052/output.txt)

I've edited the file sol-lwm2m-client.c at line 907 by removing the - (minus) before ECANCELED (I do not use lwm2m at the moment). It compiles now.
Can anyone check this issue?

Cheers,
Mattia

**Comment by ibriano** [comment]
On Wed, 03 Aug 2016 10:59:21 -0700, Mattia Antonini wrote:

> Hi!
> I'm trying to compile soletta-coap-server for RIOT but it fails, log in 
> [output.txt](https://github.com/solettaproject/soletta-small-oses-samples/files/400052/output.txt)
> 
> I've edited the file sol-lwm2m-client.c at line 907 by removing the - (minus) before ECANCELED (I do not use lwm2m at the moment). It compiles now.
> Can anyone check this issue?

Fixed in master, thanks.
